using Avalonia.Controls;
using Avalonia.Headless.XUnit;
using Avalonia.VisualTree;
using TranscribeCppSharp.Models;
using TranscribeCppSharp.Ui.Models;
using TranscribeCppSharp.Ui.ViewModels;
using TranscribeCppSharp.Ui.Views;
using Xunit;

namespace TranscribeCppSharp.Ui.Tests;

/// <summary>
/// What the Languages column and the detail pane show.
/// </summary>
/// <remarks>
/// The list comes from the model card, so these assert two things: that it renders
/// in a column that cannot hold 99 codes, and that every entry of the shipped
/// manifest actually carries one. The second is the one that matters — a manifest
/// regenerated by a tool that forgot the field would silently turn the column into
/// 72 dashes, and nothing else would notice.
/// </remarks>
public class ModelLanguagesTests
{
    /// <summary>Fixed inputs, hoisted so the analyser does not see them rebuilt per call.</summary>
    private static readonly string[] Pair = ["zh", "en"];

    private static readonly string[] Nine = ["en", "fr", "de", "es", "it", "pt", "ru", "zh", "ja"];

    private static ModelCatalogItem Item(string[]? languages)
        => new(new ModelDescriptor(
            Alias: "sample",
            Repo: "owner/sample-gguf",
            Revision: "rev",
            License: "mit",
            LicenseUrl: "https://example.invalid",
            Quant: "Q5_K_M",
            File: "sample.gguf",
            Sha256: "00",
            Size: 1,
            Languages: languages));

    [Fact]
    public void AnAbsentListRendersAsADashNotAsAnEmptyCell()
    {
        // An empty cell reads as a broken row; a dash reads as "nothing here",
        // which is the same convention the unmeasured timing column uses.
        Assert.Equal("-", Item(null).LanguagesText);
        Assert.Equal("-", Item(Array.Empty<string>()).LanguagesText);
    }

    [Fact]
    public void AShortListIsShownInFull()
    {
        Assert.Equal("zh, en", Item(Pair).LanguagesText);
    }

    [Fact]
    public void ALongListIsCutAndCounted()
    {
        // A column cannot hold nine codes, let alone the 99 some models declare.
        Assert.Equal("en, fr, de, es +5", Item(Nine).LanguagesText);
    }

    [Fact]
    public void TheDetailPaneSaysWhereTheListCameFrom()
    {
        string detail = Item(Pair).LanguagesDetail;

        // The card and the model can disagree, so the pane names its source rather
        // than presenting the manifest as a fact about the model.
        Assert.Contains("model card", detail, StringComparison.Ordinal);
        Assert.Contains("zh, en", detail, StringComparison.Ordinal);

        Assert.Contains("not stated", Item(null).LanguagesDetail, StringComparison.Ordinal);
    }

    /// <summary>
    /// Every alias the catalogue offers has to state its languages, so the column is
    /// data rather than a column of dashes.
    /// </summary>
    [Fact]
    public void EveryCatalogEntryStatesItsLanguages()
    {
        string[] missing = ModelStore.Catalog
            .Where(d => d.Languages is null || d.Languages.Length == 0)
            .Select(d => d.Alias)
            .ToArray();

        Assert.True(missing.Length == 0,
            $"{missing.Length} catalog entries declare no languages: {string.Join(", ", missing.Take(10))}");
    }

    /// <summary>The column exists, not just the property it binds.</summary>
    [Fact]
    public void EveryCatalogLanguagesListIsDistinctAndTyped()
    {
        // Guards against the field being written as a single comma-joined string by
        // whatever tool next touches the manifest: the detail pane joins them, so a
        // join of a join would double the separators.
        foreach (ModelDescriptor descriptor in ModelStore.Catalog)
        {
            Assert.NotNull(descriptor.Languages);
            Assert.All(descriptor.Languages!, code => Assert.False(code.Contains(','), code));
        }
    }

    /// <summary>
    /// The column exists and actually renders, not just the property it binds.
    /// </summary>
    /// <remarks>
    /// Realizing the row is what proves the binding: a mistyped path on a
    /// DataGridTextColumn leaves the cell blank and nothing else complains. The
    /// expected text comes from the item itself, so the grid cannot pass by
    /// disagreeing with what it was told to show.
    /// </remarks>
    [AvaloniaFact]
    public void TheGridRendersTheLanguagesOfTheModelItShows()
    {
        ModelDescriptor descriptor = ModelStore.Catalog
            .First(d => d.Languages is { Length: > 4 });
        string expected = new ModelCatalogItem(descriptor).LanguagesText;

        string previous = ModelStore.CacheRootOverride ?? string.Empty;
        bool hadOverride = ModelStore.CacheRootOverride is not null;
        try
        {
            // One row only: the expectation is about that row, not about the grid
            // being able to fit 72 of them.
            ModelStore.CacheRootOverride = Path.Combine(
                Path.GetTempPath(), "tcsharp-ui-tests-language-grid");
            var viewModel = new ModelManagerViewModel { Filter = descriptor.Alias };
            var view = new ModelManagerView { DataContext = viewModel };
            var window = new Window { Content = view, Width = 1100, Height = 720 };
            window.Show();

            Assert.Single(viewModel.VisibleModels);

            HashSet<string> rendered = window.GetVisualDescendants()
                .OfType<TextBlock>()
                .Where(t => t.IsVisible && !string.IsNullOrEmpty(t.Text))
                .Select(t => t.Text!)
                .ToHashSet();

            Assert.Contains(expected, rendered);
        }
        finally
        {
            ModelStore.CacheRootOverride = hadOverride ? previous : null;
        }
    }
}