using System.Text;
using System.Text.RegularExpressions;

namespace TranscribeCppSharp.Generator;

/// <summary>
/// Generates C# P/Invoke declarations from parsed Rust FFI.
/// </summary>
public class CSharpGenerator
{
    private readonly string _dllName = "transcribe";

    private static readonly (string Pattern, string Category)[] s_functionCategories =
    [
        ("model_load_params", "Model"), ("model_free", "Model"), ("model_", "Model"),
        ("session_init", "Session"), ("session_free", "Session"),
        ("session_limits", "Session"), ("session_", "Session"),
        ("stream_", "Streaming"), ("batch_", "Batch"), ("run_batch", "Batch"),
        ("run_params", "Run"), ("run", "Run"),
        ("segment_", "Results — Segments"), ("word_", "Results — Words"),
        ("token", "Results — Tokens"), ("speaker_", "Results — Speaker"),
        ("timing", "Timings"), ("backend", "Backend"), ("device", "Backend"),
        ("log_", "Logging"), ("version", "Version"), ("abi_", "ABI Metadata"),
        ("open", "Lifecycle"), ("close", "Lifecycle"), ("get_model", "Lifecycle"),
        ("init_backends", "Backend"), ("capabilities", "Model"), ("supports", "Model"),
        ("arch_string", "Model"), ("variant_string", "Model"), ("meta_val", "Model"),
        ("set_abort", "Cancellation"), ("was_aborted", "Cancellation"),
        ("was_truncated", "Cancellation"), ("n_segments", "Results"),
        ("n_words", "Results"), ("n_tokens", "Results"), ("full_text", "Results"),
        ("raw_text", "Results"), ("detected_language", "Results"),
        ("returned_timestamp", "Results"), ("get_segment", "Results"),
        ("get_word", "Results"), ("get_token", "Results"), ("get_timings", "Results"),
        ("print_timings", "Results"), ("reset_timings", "Results"),
        ("tokenize", "Tokenize"), ("status_string", "Status"),
    ];

    private static readonly HashSet<string> s_opaqueHandleNames =
    [
        "transcribe_model", "transcribe_session",
    ];

    private static readonly HashSet<string> s_csharpKeywords =
    [
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
        "checked", "class", "const", "continue", "decimal", "default", "delegate",
        "do", "double", "else", "enum", "event", "explicit", "extern", "false",
        "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
        "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
        "new", "null", "object", "operator", "out", "override", "params", "private",
        "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this",
        "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe",
        "ushort", "using", "virtual", "void", "volatile", "while",
        "value", "add", "remove", "get", "set",
    ];

    // ── Public API ─────────────────────────────────────────────────

    public string Generate(RustFfiParser parser)
    {
        var sb = new StringBuilder();
        WriteHeader(sb);
        WriteEnums(sb, parser);
        WriteHandles(sb);
        WriteCallbacks(sb);
        WriteStructs(sb, parser);
        WriteFunctions(sb, parser);
        return sb.ToString();
    }

    // ── Write sections ─────────────────────────────────────────────

    private void WriteHeader(StringBuilder sb)
    {
        sb.AppendLine("""
            // <auto-generated/>
            // Generated by TranscribeCppSharp.Generator from transcribe_sys.rs
            // Source: https://github.com/handy-computer/transcribe.cpp
            // DO NOT EDIT — regenerate with: dotnet run --project src/Generator

            #nullable enable

            using System;
            using System.Runtime.InteropServices;

            namespace TranscribeCppSharp.Interop;
            """);
    }

    private void WriteEnums(StringBuilder sb, RustFfiParser parser)
    {
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("// Enums");
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        foreach (var e in parser.ParseEnums())
            WriteEnum(sb, e);
    }

    private void WriteHandles(StringBuilder sb)
    {
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("// Typed handles (opaque pointers with compile-time safety)");
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        WriteHandle(sb, "ModelHandle");
        WriteHandle(sb, "SessionHandle");
    }

    private void WriteCallbacks(StringBuilder sb)
    {
        sb.AppendLine("""
            // ════════════════════════════════════════════════════════════════
            // Callback delegates
            //
            // These are hand-written because the Rust FFI uses
            //   pub type transcribe_log_callback = Option<unsafe extern "C" fn(...)>
            // which the parser cannot expand into a callable signature.
            //
            // NAMING CONTRACT: ToPascalCase("transcribe_<name>_callback") must
            // produce the delegate name below (e.g. "transcribe_log_callback"
            // → "LogCallback"). If a new callback is added to transcribe_sys.rs,
            // add a matching delegate here with the same convention.
            // ════════════════════════════════════════════════════════════════
            [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
            public delegate void LogCallback(LogLevel level, [MarshalAs(UnmanagedType.LPUTF8Str)] string msg, IntPtr userdata);

            [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
            [return: MarshalAs(UnmanagedType.U1)]
            public delegate bool AbortCallback(IntPtr userdata);
            """);
    }

    private void WriteStructs(StringBuilder sb, RustFfiParser parser)
    {
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("// Structs");
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        foreach (var s in parser.ParseStructs())
            WriteStruct(sb, s);
    }

    private void WriteFunctions(StringBuilder sb, RustFfiParser parser)
    {
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("// Native functions");
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("internal static partial class NativeMethods");
        sb.AppendLine("{");
        sb.AppendLine($"    private const string LibName = \"{_dllName}\";");
        sb.AppendLine();

        var functions = parser.ParseFunctions();
        var grouped = functions.GroupBy(f => ClassifyFunction(f.Name));
        foreach (var group in grouped.OrderBy(g => g.Key))
        {
            sb.AppendLine($"    // ── {group.Key} ──");
            foreach (var fn in group)
                WriteFunction(sb, fn);
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    // ── Write individual elements ──────────────────────────────────

    private void WriteEnum(StringBuilder sb, RustEnum e)
    {
        var csName = ToPascalCase(e.TypeName);
        sb.AppendLine($"public enum {csName}");
        sb.AppendLine("{");
        foreach (var v in e.Values)
            sb.AppendLine($"    {ToPascalCase(v.Name)} = {v.Value},");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private void WriteHandle(StringBuilder sb, string csName)
    {
        sb.AppendLine($$"""
            [StructLayout(LayoutKind.Sequential)]
            public readonly struct {{csName}} : IEquatable<{{csName}}>
            {
                internal readonly IntPtr Value;
                internal {{csName}}(IntPtr value) => Value = value;

                public static implicit operator IntPtr({{csName}} h) => h.Value;
                public static explicit operator {{csName}}(IntPtr v) => new(v);
                public static {{csName}} Null => new(IntPtr.Zero);
                public bool IsNull => Value == IntPtr.Zero;

                public bool Equals({{csName}} other) => Value == other.Value;
                public override bool Equals(object? obj) => obj is {{csName}} h && Equals(h);
                public override int GetHashCode() => Value.GetHashCode();
                public override string ToString() => $"{{csName}}(0x{Value:X})";

                public static bool operator ==({{csName}} left, {{csName}} right) => left.Equals(right);
                public static bool operator !=({{csName}} left, {{csName}} right) => !left.Equals(right);
            }
            """);
        sb.AppendLine();
    }

    private void WriteStruct(StringBuilder sb, RustStruct s)
    {
        var csName = ToPascalCase(s.Name);
        sb.AppendLine("[StructLayout(LayoutKind.Sequential, Pack = 8)]");
        sb.AppendLine($"public struct {csName}");
        sb.AppendLine("{");
        foreach (var f in s.Fields)
        {
            var csField = ToCamelCase(f.Name);

            // Bool fields: MUST be 1 byte (Rust repr(C) bool = 1 byte)
            if (f.Type is BoolType)
                sb.AppendLine("    [MarshalAs(UnmanagedType.I1)]");

            var csType = MapStructFieldType(f.Type);
            sb.AppendLine($"    public {csType} {csField};");
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private void WriteFunction(StringBuilder sb, RustFunction fn)
    {
        var csName = ToPascalCase(fn.Name);

        // Skip functions with callback pointer params (need manual delegate mapping)
        if (fn.Parameters.Any(p => IsFunctionPointer(p.Type)))
        {
            sb.AppendLine($"    // TODO: {fn.Name} — function pointer params need manual delegate mapping");
            sb.AppendLine();
            return;
        }

        // Determine return type — borrowed string pointers return IntPtr
        var isBorrowedStringReturn = fn.ReturnType is PointerType(_, PrimitiveType("c_char"));
        var retCsType = isBorrowedStringReturn ? "IntPtr" : MapParamType(fn.ReturnType);

        sb.AppendLine($"    [LibraryImport(LibName, EntryPoint = \"{fn.Name}\", StringMarshalling = StringMarshalling.Utf8)]");

        // Bool return: must be U1 (1 byte, not 4-byte Windows BOOL)
        if (fn.ReturnType is BoolType)
            sb.AppendLine("    [return: MarshalAs(UnmanagedType.U1)]");

        var paramsStr = string.Join(", ", fn.Parameters.Select(p =>
        {
            var name = ToCamelCase(p.Name);
            return p.Type switch
            {
                // Immutable pointer to char → input string (StringMarshalling.Utf8 handles it)
                PointerType(PointerMutability.Const, PrimitiveType("c_char"))
                    => $"string {name}",
                // Mutable pointer to char → output buffer (IntPtr)
                PointerType(PointerMutability.Mutable, PrimitiveType("c_char"))
                    => $"IntPtr {name}",
                // Bool param: must be I1 (1 byte)
                BoolType
                    => $"[MarshalAs(UnmanagedType.I1)] bool {name}",
                // Everything else
                _ => $"{MapParamType(p.Type)} {name}",
            };
        }));

        sb.AppendLine($"    public static partial {retCsType} {csName}({paramsStr});");
        sb.AppendLine();
    }

    // ── Type mapping — structural, no string matching ───────────────

    /// <summary>
    /// Map a Rust type to its C# equivalent for function parameters and return values.
    /// </summary>
    private static string MapParamType(RustType rustType) => rustType switch
    {
        VoidType => "void",
        BoolType => "bool",
        PrimitiveType("i32") => "int",
        PrimitiveType("u32") => "uint",
        PrimitiveType("i64") => "long",
        PrimitiveType("u64") => "ulong",
        PrimitiveType("usize") or PrimitiveType("nuint") => "nuint",
        PrimitiveType("f32") => "float",
        PrimitiveType("f64") => "double",
        PrimitiveType("c_int") => "int",
        PrimitiveType("c_uint") => "uint",
        PrimitiveType("c_char") => "byte",

        // Opaque handles → typed handle struct
        PointerType(_, OpaqueHandleType("transcribe_model")) => "ModelHandle",
        PointerType(_, OpaqueHandleType("transcribe_session")) => "SessionHandle",

        // Named struct types (by pointer)
        PointerType(_, StructType(var rustName)) => $"IntPtr /* {rustName} */",
        StructType(var rustName) => ToPascalCase(rustName),

        // All other pointer types → IntPtr
        PointerType => "IntPtr",

        UnknownType(var raw) => $"/* UNKNOWN: {raw} */ object",
        _ => throw new NotSupportedException($"Unhandled Rust type: {rustType}"),
    };

    /// <summary>
    /// Map a Rust type for struct field context.
    /// Bool gets MarshalAs I1, borrowed string pointers become IntPtr.
    /// </summary>
    private static string MapStructFieldType(RustType rustType) => rustType switch
    {
        // Borrowed string pointers in structs → IntPtr (caller marshals manually)
        PointerType(_, PrimitiveType("c_char")) => "IntPtr",
        // Double pointer to char → IntPtr (e.g. *const *const c_char)
        PointerType(_, PointerType(_, PrimitiveType("c_char"))) => "IntPtr",
        // All other types: same as param mapping
        _ => MapParamType(rustType),
    };

    private static bool IsFunctionPointer(RustType rustType) => rustType switch
    {
        // Option<unsafe fn(...)> shows up as UnknownType from the parser
        UnknownType(var raw) => raw.Contains("Option<unsafe"),
        _ => false,
    };

    // ── Helpers ────────────────────────────────────────────────────

    private static string ClassifyFunction(string name)
    {
        foreach (var (pattern, category) in s_functionCategories)
        {
            if (name == pattern || name.StartsWith(pattern))
                return category;
        }
        return "Misc";
    }

    private static string ToPascalCase(string s)
    {
        s = Regex.Replace(s, @"^transcribe_", "", RegexOptions.IgnoreCase);
        return string.Join("", s.Split('_', StringSplitOptions.RemoveEmptyEntries)
            .Select(w => w.All(char.IsUpper)
                ? char.ToUpper(w[0]) + (w.Length > 1 ? w[1..].ToLower() : "")
                : char.ToUpper(w[0]) + (w.Length > 1 ? w[1..] : "")));
    }

    private static string ToCamelCase(string s)
    {
        var pascal = ToPascalCase(s);
        var camel = pascal.Length > 0 ? char.ToLower(pascal[0]) + pascal[1..] : pascal;
        return s_csharpKeywords.Contains(camel) ? "@" + camel : camel;
    }
}
