using System.Text;
using System.Text.RegularExpressions;
using static System.Globalization.CultureInfo;

namespace TranscribeCppSharp.Generator;

/// <summary>
/// Generates C# P/Invoke declarations from parsed Rust FFI.
/// </summary>
public class CSharpGenerator
{
    private readonly string dllName = "transcribe";

    private static readonly (string Pattern, string Category)[] FunctionCategories =
    [
        ("model_load_params", "Model"), ("model_free", "Model"), ("model_", "Model"),
        ("session_init", "Session"), ("session_free", "Session"),
        ("session_limits", "Session"), ("session_", "Session"),
        ("stream_", "Streaming"), ("batch_", "Batch"), ("run_batch", "Batch"),
        ("run_params", "Run"), ("run", "Run"),
        ("segment_", "Results — Segments"), ("word_", "Results — Words"),
        ("token", "Results — Tokens"), ("speaker_", "Results — Speaker"),
        ("timing", "Timings"), ("backend", "Backend"), ("device", "Backend"),
        ("log_", "Logging"), ("version", "Version"), ("abi_", "ABI Metadata"),
        ("open", "Lifecycle"), ("close", "Lifecycle"), ("get_model", "Lifecycle"),
        ("init_backends", "Backend"), ("capabilities", "Model"), ("supports", "Model"),
        ("arch_string", "Model"), ("variant_string", "Model"), ("meta_val", "Model"),
        ("set_abort", "Cancellation"), ("was_aborted", "Cancellation"),
        ("was_truncated", "Cancellation"), ("n_segments", "Results"),
        ("n_words", "Results"), ("n_tokens", "Results"), ("full_text", "Results"),
        ("raw_text", "Results"), ("detected_language", "Results"),
        ("returned_timestamp", "Results"), ("get_segment", "Results"),
        ("get_word", "Results"), ("get_token", "Results"), ("get_timings", "Results"),
        ("print_timings", "Results"), ("reset_timings", "Results"),
        ("tokenize", "Tokenize"), ("status_string", "Status"),
    ];

    private static readonly HashSet<string> OpaqueHandleNames =
    [
        "transcribe_model", "transcribe_session",
    ];

    private static readonly HashSet<string> CsharpKeywords =
    [
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
        "checked", "class", "const", "continue", "decimal", "default", "delegate",
        "do", "double", "else", "enum", "event", "explicit", "extern", "false",
        "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
        "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
        "new", "null", "object", "operator", "out", "override", "params", "private",
        "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this",
        "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe",
        "ushort", "using", "virtual", "void", "volatile", "while",
        "value", "add", "remove", "get", "set",
    ];

    // ── Public API ─────────────────────────────────────────────────
    public string Generate(RustFfiParser parser, CHeaderDoc? headerDoc = null)
    {
        var sb = new StringBuilder();
        WriteHeader(sb);
        WriteEnums(sb, parser, headerDoc);
        WriteHandles(sb);
        WriteCallbacks(sb, headerDoc);
        WriteStructs(sb, parser, headerDoc);
        WriteAbiLayout(sb, parser);
        WriteFunctions(sb, parser, headerDoc);
        return sb.ToString();
    }

    // ── Write sections ─────────────────────────────────────────────
    private static void WriteHeader(StringBuilder sb)
    {
        sb.AppendLine("""
            // <auto-generated/>
            // Generated by TranscribeCppSharp.Generator from transcribe_sys.rs
            // Source: https://github.com/handy-computer/transcribe.cpp
            // DO NOT EDIT — regenerate with: dotnet run --project src/Generator

            #nullable enable

            using System;
            using System.Runtime.InteropServices;

            namespace TranscribeCppSharp.Interop;
            """);
    }

    private static void WriteEnums(StringBuilder sb, RustFfiParser parser, CHeaderDoc? headerDoc)
    {
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("// Enums");
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        foreach (var e in parser.ParseEnums())
        {
            WriteEnum(sb, e, headerDoc);
        }
    }

    private static void WriteHandles(StringBuilder sb)
    {
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("// Typed handles (opaque pointers with compile-time safety)");
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        WriteHandle(sb, "ModelHandle");
        WriteHandle(sb, "SessionHandle");
    }

    private static void WriteCallbacks(StringBuilder sb, CHeaderDoc? headerDoc)
    {
        sb.AppendLine("""
            // ════════════════════════════════════════════════════════════════
            // Callback delegates
            //
            // These are hand-written because the Rust FFI uses
            //   pub type transcribe_log_callback = Option<unsafe extern "C" fn(...)>
            // which the parser cannot expand into a callable signature.
            //
            // NAMING CONTRACT: ToPascalCase("transcribe_<name>_callback") must
            // produce the delegate name below (e.g. "transcribe_log_callback"
            // → "LogCallback"). If a new callback is added to transcribe_sys.rs,
            // add a matching delegate here with the same convention.
            // ════════════════════════════════════════════════════════════════

            /// <summary>
            /// Receives log messages from the native library. May be invoked from any
            /// thread (including ggml worker threads); see transcribe_log_set.
            /// </summary>
            [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
            public delegate void LogCallback(LogLevel level, [MarshalAs(UnmanagedType.LPUTF8Str)] string msg, IntPtr userdata);

            /// <summary>
            /// Polled by the native library between chunks and decode steps; returning
            /// true aborts the in-flight run. See transcribe_set_abort_callback.
            /// </summary>
            [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
            [return: MarshalAs(UnmanagedType.U1)]
            public delegate bool AbortCallback(IntPtr userdata);
            """);
    }

    private static void WriteStructs(StringBuilder sb, RustFfiParser parser, CHeaderDoc? headerDoc)
    {
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("// Structs");
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        foreach (var s in parser.ParseStructs())
        {
            // Skip opaque handles — they're represented as SafeHandle classes, not structs
            if (OpaqueHandleNames.Contains(s.Name))
            {
                continue;
            }

            // Skip empty structs (parsed from opaque types with no public fields)
            if (s.Fields.Count == 0)
            {
                Console.Error.WriteLine($"Warning: skipping empty struct '{s.Name}' (no public fields)");
                continue;
            }

            WriteStruct(sb, s, headerDoc);
        }
    }

    private void WriteFunctions(StringBuilder sb, RustFfiParser parser, CHeaderDoc? headerDoc)
    {
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("// Native functions");
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("internal static partial class NativeMethods");
        sb.AppendLine("{");
        sb.AppendLine(InvariantCulture, $"    private const string LibName = \"{dllName}\";");
        sb.AppendLine();

        var functions = parser.ParseFunctions();
        var grouped = functions.GroupBy(f => ClassifyFunction(f.Name));
        foreach (var group in grouped.OrderBy(g => g.Key))
        {
            sb.AppendLine(InvariantCulture, $"    // ── {group.Key} ──");
            foreach (var fn in group)
            {
                WriteFunction(sb, fn, headerDoc);
            }

            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    /// <summary>
    /// Emit the ABI layout contract: total size, alignment and per-field offsets for every
    /// struct, extracted from the compile-time checks in transcribe_sys.rs (size_of!,
    /// align_of!, offset_of!). These are verified by the Rust compiler against the real
    /// repr(C) layout, so they lock the C# struct declarations to the native ground truth
    /// (64-bit platforms — the only ones this library ships).
    /// </summary>
    private static void WriteAbiLayout(StringBuilder sb, RustFfiParser parser)
    {
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("// ABI layout contracts (native ground truth)");
        sb.AppendLine("// Sizes/alignments/offsets come from the compile-time checks emitted");
        sb.AppendLine("// by bindgen in transcribe_sys.rs (size_of!/align_of!/offset_of!).");
        sb.AppendLine("// AbiLayoutTest cross-checks Marshal.SizeOf/OffsetOf against these.");
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("internal static class AbiLayout");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly (string TypeName, ulong Size, ulong Align, (string Field, nuint Offset)[] Offsets)[] All =");
        sb.AppendLine("    [");
        foreach (var layout in parser.ParseAbiLayouts())
        {
            var csName = ToPascalCase(layout.Name);
            var fields = string.Join(", ", layout.Fields.Select(f => $"(\"{ToCamelCase(f.Field)}\", {f.Offset})"));
            sb.AppendLine(InvariantCulture, $"        (\"{csName}\", {layout.Size}, {layout.Align}, [{fields}]),");
        }

        sb.AppendLine("    ];");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ── Write individual elements ──────────────────────────────────
    private static void WriteEnum(StringBuilder sb, RustEnumDecl e, CHeaderDoc? headerDoc)
    {
        var csName = ToPascalCase(e.TypeName);
        var doc = headerDoc?.GetEnumDoc(e.TypeName);
        if (!string.IsNullOrEmpty(doc))
        {
            WriteXmlDoc(sb, doc, string.Empty);
        }

        sb.AppendLine(InvariantCulture, $"public enum {csName}");
        sb.AppendLine("{");
        foreach (var v in e.Values)
        {
            var valueDoc = headerDoc?.GetEnumValueDoc(e.TypeName, v.Name);
            if (!string.IsNullOrEmpty(valueDoc))
            {
                sb.AppendLine();
                WriteXmlDoc(sb, valueDoc, "    ");
            }

            sb.AppendLine(InvariantCulture, $"    {ToPascalCase(v.Name)} = {v.Value},");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void WriteHandle(StringBuilder sb, string csName)
    {
        var freeMethod = csName switch
        {
            "ModelHandle" => "ModelFree",
            "SessionHandle" => "SessionFree",
            _ => throw new InvalidOperationException($"Unknown handle type: {csName}"),
        };

        var owner = csName == "ModelHandle" ? "model" : "session";

        var handleTemplate = $$"""
            /// <summary>
            /// Owns the native {{owner}} instance and releases it via
            /// <see cref="NativeMethods.{{freeMethod}}"/> on finalization/Dispose.
            /// Created only through <c>transcribe_{{owner}}_new</c> or
            /// <c>transcribe_{{owner}}_init</c>; never instantiate directly.
            /// Not thread-safe: a handle must not be shared across threads without
            /// external synchronization.
            /// </summary>
            public sealed class {{csName}} : SafeHandle
            {
                public static readonly {{csName}} Null = new {{csName}}(IntPtr.Zero);

                public {{csName}}() : base(IntPtr.Zero, true) { }
                public {{csName}}(IntPtr handle) : base(IntPtr.Zero, true) => SetHandle(handle);

                public override bool IsInvalid => handle == IntPtr.Zero;

                protected override bool ReleaseHandle()
                {
                    NativeMethods.{{freeMethod}}(handle);
                    return true;
                }

                public static implicit operator IntPtr({{csName}} h) => h.handle;
                public static explicit operator {{csName}}(IntPtr v) => new {{csName}}(v);

                public override string ToString() => $"{{csName}}(0x{handle:X})";
            }
            """;
        sb.AppendLine(handleTemplate);
        sb.AppendLine();
    }

    private static void WriteStruct(StringBuilder sb, RustStruct s, CHeaderDoc? headerDoc)
    {
        var csName = ToPascalCase(s.Name);
        var doc = headerDoc?.GetStructDoc(s.Name);
        if (!string.IsNullOrEmpty(doc))
        {
            WriteXmlDoc(sb, doc, string.Empty);
        }

        sb.AppendLine("[StructLayout(LayoutKind.Sequential, Pack = 8)]");
        sb.AppendLine(InvariantCulture, $"public struct {csName}");
        sb.AppendLine("{");
        foreach (var f in s.Fields)
        {
            var csField = ToCamelCase(f.Name);

            var fieldDoc = headerDoc?.GetStructFieldDoc(s.Name, f.Name);
            if (!string.IsNullOrEmpty(fieldDoc))
            {
                sb.AppendLine();
                WriteXmlDoc(sb, fieldDoc, "    ");
            }

            // Bool fields: MUST be 1 byte (Rust repr(C) bool = 1 byte)
            if (f.Type is BoolType)
            {
                sb.AppendLine("    [MarshalAs(UnmanagedType.I1)]");
            }

            var csType = MapStructFieldType(f.Type);
            sb.AppendLine(InvariantCulture, $"    public {csType} {csField};");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void WriteFunction(StringBuilder sb, RustFunction fn, CHeaderDoc? headerDoc)
    {
        var csName = ToPascalCase(fn.Name);

        // Skip functions with callback pointer params (need manual delegate mapping)
        if (fn.Parameters.Any(p => IsFunctionPointer(p.Type)))
        {
            Console.Error.WriteLine($"Warning: skipping '{fn.Name}' — function pointer params need manual delegate mapping");
            sb.AppendLine(InvariantCulture, $"    // Skipped: {fn.Name} — function pointer params need manual delegate mapping");
            sb.AppendLine();
            return;
        }

        var doc = headerDoc?.GetFunctionDoc(fn.Name);
        if (!string.IsNullOrEmpty(doc))
        {
            WriteXmlDoc(sb, doc, "    ");
        }

        // Determine return type — borrowed string pointers return IntPtr
        var isBorrowedStringReturn = fn.ReturnType is PointerType(_, PrimitiveType("c_char"));
        var retCsType = isBorrowedStringReturn ? "IntPtr" : MapParamType(fn.ReturnType);

        sb.AppendLine(InvariantCulture, $"    [LibraryImport(LibName, EntryPoint = \"{fn.Name}\", StringMarshalling = StringMarshalling.Utf8)]");

        // Bool return: must be U1 (1 byte, not 4-byte Windows BOOL)
        if (fn.ReturnType is BoolType)
        {
            sb.AppendLine("    [return: MarshalAs(UnmanagedType.U1)]");
        }

        var paramsStr = string.Join(", ", fn.Parameters.Select(p =>
        {
            var name = ToCamelCase(p.Name);
            return p.Type switch
            {
                // Immutable pointer to char → input string (StringMarshalling.Utf8 handles it)
                PointerType(PointerMutability.Const, PrimitiveType("c_char"))
                    => $"string {name}",

                // Mutable pointer to char → output buffer (IntPtr)
                PointerType(PointerMutability.Mutable, PrimitiveType("c_char"))
                    => $"IntPtr {name}",

                // Bool param: must be I1 (1 byte)
                BoolType
                    => $"[MarshalAs(UnmanagedType.I1)] bool {name}",

                // Everything else
                _ => $"{MapParamType(p.Type)} {name}",
            };
        }));

        sb.AppendLine(InvariantCulture, $"    public static partial {retCsType} {csName}({paramsStr});");
        sb.AppendLine();
    }

    // ── Type mapping — structural, no string matching ───────────────

    /// <summary>
    /// Map a Rust type to its C# equivalent for function parameters and return values.
    /// </summary>
    private static string MapParamType(RustType rustType) => rustType switch
    {
        VoidType => "void",
        BoolType => "bool",
        PrimitiveType("i32") => "int",
        PrimitiveType("u32") => "uint",
        PrimitiveType("i64") => "long",
        PrimitiveType("u64") => "ulong",
        PrimitiveType("usize") or PrimitiveType("nuint") => "nuint",
        PrimitiveType("f32") => "float",
        PrimitiveType("f64") => "double",
        PrimitiveType("c_int") => "int",
        PrimitiveType("c_uint") => "uint",
        PrimitiveType("c_char") => "byte",

        // Opaque handles → IntPtr (P/Invoke works with raw pointers)
        PointerType(_, OpaqueHandleType("transcribe_model")) => "IntPtr",
        PointerType(_, OpaqueHandleType("transcribe_session")) => "IntPtr",

        // Named struct types (by pointer)
        PointerType(_, StructType(var rustName)) => $"IntPtr /* {rustName} */",
        StructType(var rustName) => ToPascalCase(rustName),

        // All other pointer types → IntPtr
        PointerType => "IntPtr",

        UnknownType(var raw) => throw new InvalidOperationException(
            $"Unknown Rust type in FFI binding: '{raw}'. " +
            $"Add a mapping in MapParamType or handle it as a known type."),
        _ => throw new NotSupportedException($"Unhandled Rust type: {rustType}"),
    };

    /// <summary>
    /// Map a Rust type for struct field context.
    /// Bool gets MarshalAs I1, borrowed string pointers become IntPtr.
    /// </summary>
    private static string MapStructFieldType(RustType rustType) => rustType switch
    {
        // Borrowed string pointers in structs → IntPtr (caller marshals manually)
        PointerType(_, PrimitiveType("c_char")) => "IntPtr",

        // Double pointer to char → IntPtr (e.g. *const *const c_char)
        PointerType(_, PointerType(_, PrimitiveType("c_char"))) => "IntPtr",

        // All other types: same as param mapping
        _ => MapParamType(rustType),
    };

    private static bool IsFunctionPointer(RustType rustType) => rustType switch
    {
        // Option<unsafe fn(...)> shows up as UnknownType from the parser
        UnknownType(var raw) => raw.Contains("Option<unsafe"),
        _ => false,
    };

    // ── Helpers ────────────────────────────────────────────────────

    /// <summary>
    /// Emits a doc comment from the upstream C header as XML documentation,
    /// wrapped in &lt;summary&gt; with &lt;para&gt; paragraph breaks and
    /// &lt;list type="bullet"&gt; for bullet blocks ("- " lines), so IDEs render
    /// it properly (multi-paragraph C docs would otherwise collapse into one
    /// blob). Strips /* */ markers, un-indents, and escapes XML-significant
    /// characters.
    /// </summary>
    private static void WriteXmlDoc(StringBuilder sb, string doc, string indent)
    {
        sb.AppendLine(InvariantCulture, $"{indent}/// <summary>");
        var lines = doc.Split('\n');
        var inParagraph = false;

        for (int i = 0; i < lines.Length; i++)
        {
            var trimmed = lines[i].Trim();
            if (trimmed.Length == 0)
            {
                if (inParagraph)
                {
                    sb.AppendLine(InvariantCulture, $"{indent}/// </para>");
                    inParagraph = false;
                }

                continue;
            }

            if (trimmed.StartsWith("- ", StringComparison.Ordinal))
            {
                // Close any open paragraph before starting list markup.
                if (inParagraph)
                {
                    sb.AppendLine(InvariantCulture, $"{indent}/// </para>");
                    inParagraph = false;
                }

                sb.AppendLine(InvariantCulture, $"{indent}/// <list type=\"bullet\">");

                while (i < lines.Length)
                {
                    var bullet = lines[i].Trim();
                    if (bullet.Length == 0)
                    {
                        break;
                    }

                    if (!bullet.StartsWith("- ", StringComparison.Ordinal))
                    {
                        break;
                    }

                    sb.AppendLine(InvariantCulture, $"{indent}/// <item>");
                    sb.AppendLine(InvariantCulture, $"{indent}/// <description>");
                    sb.AppendLine(InvariantCulture, $"{indent}/// {EscapeXml(bullet[2..])}");
                    i++;
                    while (i < lines.Length && lines[i].Trim().Length > 0 &&
                           !lines[i].Trim().StartsWith("- ", StringComparison.Ordinal))
                    {
                        sb.AppendLine(InvariantCulture, $"{indent}/// {EscapeXml(lines[i].Trim())}");
                        i++;
                    }

                    sb.AppendLine(InvariantCulture, $"{indent}/// </description>");
                    sb.AppendLine(InvariantCulture, $"{indent}/// </item>");
                }

                sb.AppendLine(InvariantCulture, $"{indent}/// </list>");
                continue;
            }

            if (!inParagraph)
            {
                sb.AppendLine(InvariantCulture, $"{indent}/// <para>");
                inParagraph = true;
            }

            sb.AppendLine(InvariantCulture, $"{indent}/// {EscapeXml(trimmed)}");
        }

        if (inParagraph)
        {
            sb.AppendLine(InvariantCulture, $"{indent}/// </para>");
        }

        sb.AppendLine(InvariantCulture, $"{indent}/// </summary>");
    }

    private static readonly Regex BacktickRegex = new("`([^`]+)`", RegexOptions.Compiled);

    /// <summary>
    /// Escapes the two XML-significant characters that are mandatory in element
    /// text (&lt; and &amp;; a bare &gt; is valid XML text), then converts
    /// Markdown-style backtick spans (as used by the upstream C header) into the
    /// XML doc inline-code element &lt;c&gt;. Without this, `` `code` `` renders
    /// as literal backticks in IDE tooltips instead of code formatting.
    /// </summary>
    private static string EscapeXml(string s)
    {
        var escaped = s
            .Replace("&", "&amp;")
            .Replace("<", "&lt;");
        return BacktickRegex.Replace(escaped, m => $"<c>{m.Groups[1].Value}</c>");
    }

    private static string ClassifyFunction(string name)
    {
        foreach (var (pattern, category) in FunctionCategories)
        {
            if (name == pattern || name.StartsWith(pattern, StringComparison.Ordinal))
            {
                return category;
            }
        }

        return "Misc";
    }

    private static string ToPascalCase(string s)
    {
        s = Regex.Replace(s, @"^transcribe_", string.Empty, RegexOptions.IgnoreCase);
        return string.Join(string.Empty, s.Split('_', StringSplitOptions.RemoveEmptyEntries)
            .Select(w => w.All(char.IsUpper)
                ? char.ToUpperInvariant(w[0]) + (w.Length > 1 ? w[1..].ToLowerInvariant() : string.Empty)
                : char.ToUpperInvariant(w[0]) + (w.Length > 1 ? w[1..] : string.Empty)));
    }

    private static string ToCamelCase(string s)
    {
        var pascal = ToPascalCase(s);
        var camel = pascal.Length > 0 ? char.ToLowerInvariant(pascal[0]) + pascal[1..] : pascal;
        return CsharpKeywords.Contains(camel) ? "@" + camel : camel;
    }
}
