using System.Text;
using System.Text.RegularExpressions;

namespace TranscribeCppSharp.Generator;

/// <summary>
/// Generates C# P/Invoke declarations from parsed Rust FFI.
/// </summary>
public class CSharpGenerator
{
    private readonly string _dllName = "transcribe";

    // Opaque handle types: Rust pointer → C# typed handle
    private static readonly Dictionary<string, string> s_opaqueHandles = new()
    {
        ["transcribe_model"] = "ModelHandle",
        ["transcribe_session"] = "SessionHandle",
    };

    public string Generate(RustFfiParser parser)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by TranscribeCppSharp.Generator from transcribe_sys.rs");
        sb.AppendLine("// Source: https://github.com/handy-computer/transcribe.cpp");
        sb.AppendLine("// DO NOT EDIT — regenerate with: dotnet run --project src/Generator");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.AppendLine("namespace TranscribeCppSharp.Interop;");
        sb.AppendLine();

        // ── Enums ──
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("// Enums");
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        foreach (var e in parser.ParseEnums())
            sb.Append(GenerateEnum(e));

        // ── Typed handles ──
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("// Typed handles (opaque pointers with compile-time safety)");
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        foreach (var (rustType, csName) in s_opaqueHandles)
            sb.Append(GenerateHandle(csName));
        sb.AppendLine();

        // ── Callback delegates ──
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("// Callback delegates");
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("[UnmanagedFunctionPointer(CallingConvention.Cdecl)]");
        sb.AppendLine("public delegate void LogCallback(LogLevel level, [MarshalAs(UnmanagedType.LPStr)] string msg, IntPtr userdata);");
        sb.AppendLine();
        sb.AppendLine("[UnmanagedFunctionPointer(CallingConvention.Cdecl)]");
        sb.AppendLine("[return: MarshalAs(UnmanagedType.U1)]");
        sb.AppendLine("public delegate bool AbortCallback(IntPtr userdata);");
        sb.AppendLine();

        // ── Structs ──
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("// Structs");
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        foreach (var s in parser.ParseStructs())
            sb.Append(GenerateStruct(s));

        // ── Functions ──
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("// Native functions");
        sb.AppendLine("// ════════════════════════════════════════════════════════════════");
        sb.AppendLine("internal static partial class NativeMethods");
        sb.AppendLine("{");
        sb.AppendLine($"    private const string LibName = \"{_dllName}\";");
        sb.AppendLine();

        var functions = parser.ParseFunctions();
        var grouped = functions.GroupBy(f => ClassifyFunction(f.Name));
        foreach (var group in grouped.OrderBy(g => g.Key))
        {
            sb.AppendLine($"    // ── {group.Key} ──");
            foreach (var fn in group)
                sb.Append(GenerateFunction(fn));
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private string GenerateHandle(string csName)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"[StructLayout(LayoutKind.Sequential)]");
        sb.AppendLine($"public readonly struct {csName}");
        sb.AppendLine("{");
        sb.AppendLine($"    internal readonly IntPtr Value;");
        sb.AppendLine($"    internal {csName}(IntPtr value) => Value = value;");
        sb.AppendLine($"    public static implicit operator IntPtr({csName} h) => h.Value;");
        sb.AppendLine($"    public static explicit operator {csName}(IntPtr v) => new(v);");
        sb.AppendLine($"    public static {csName} Null => new(IntPtr.Zero);");
        sb.AppendLine($"    public bool IsNull => Value == IntPtr.Zero;");
        sb.AppendLine("}");
        sb.AppendLine();
        return sb.ToString();
    }

    private string GenerateEnum(RustEnum e)
    {
        var sb = new StringBuilder();
        var csName = ToPascalCase(e.TypeName);
        sb.AppendLine($"public enum {csName}");
        sb.AppendLine("{");
        foreach (var v in e.Values)
        {
            var csValue = ToPascalCase(v.Name);
            sb.AppendLine($"    {csValue} = {v.Value},");
        }
        sb.AppendLine("}");
        sb.AppendLine();
        return sb.ToString();
    }

    private string GenerateStruct(RustStruct s)
    {
        var sb = new StringBuilder();
        var csName = ToPascalCase(s.Name);
        sb.AppendLine($"[StructLayout(LayoutKind.Sequential)]");
        sb.AppendLine($"public struct {csName}");
        sb.AppendLine("{");
        foreach (var f in s.Fields)
        {
            var csType = MapType(f.Type);
            var csField = ToCamelCase(f.Name);
            if (f.Type.Contains("*const c_char"))
                sb.AppendLine($"    [MarshalAs(UnmanagedType.LPStr)]");
            sb.AppendLine($"    public {csType} {csField};");
        }
        sb.AppendLine("}");
        sb.AppendLine();
        return sb.ToString();
    }

    private string GenerateFunction(RustFunction fn)
    {
        var sb = new StringBuilder();
        var csName = ToPascalCase(fn.Name);
        var retType = MapType(fn.ReturnType);

        if (fn.ParamsRaw.Contains("Option<unsafe"))
        {
            sb.AppendLine($"    // SKIPPED: {fn.Name} (function pointer callback — declare manually)");
            sb.AppendLine();
            return sb.ToString();
        }

        sb.AppendLine($"    [LibraryImport(LibName, EntryPoint = \"{fn.Name}\", StringMarshalling = StringMarshalling.Utf8)]");

        if (retType == "string" || fn.ReturnType.Contains("*const c_char"))
            sb.AppendLine($"    [return: MarshalAs(UnmanagedType.LPStr)]");
        else if (retType == "bool")
            sb.AppendLine($"    [return: MarshalAs(UnmanagedType.U1)]");

        var parameters = ParseParams(fn.ParamsRaw);
        var paramsStr = string.Join(", ", parameters.Select(p =>
        {
            var type = MapType(p.Type);
            var name = ToCamelCase(p.Name);
            if (p.Type.Contains("*const c_char"))
                return $"[MarshalAs(UnmanagedType.LPUTF8Str)] string {name}";
            if (type == "bool")
                return $"[MarshalAs(UnmanagedType.U1)] bool {name}";
            return $"{type} {name}";
        }));

        sb.AppendLine($"    public static partial {retType} {csName}({paramsStr});");
        sb.AppendLine();
        return sb.ToString();
    }

    private string MapType(string rustType)
    {
        rustType = rustType.Trim();

        // String pointers
        if (rustType == "*const ::std::os::raw::c_char" || rustType == "*const c_char")
            return "string";

        // Opaque typed handles
        foreach (var (rustName, csHandle) in s_opaqueHandles)
        {
            if (rustType.Contains(rustName) && rustType.Contains("*"))
                return csHandle;
        }

        // Other transcribe_ pointers → IntPtr
        if (rustType.Contains("transcribe_") && rustType.Contains("*"))
            return "IntPtr";

        // Function pointer types → IntPtr
        if (rustType.Contains("Option<unsafe"))
            return "IntPtr";

        return rustType switch
        {
            "()" or "" or null => "void",
            "void" => "void",
            "bool" => "bool",
            "i32" => "int",
            "u32" => "uint",
            "i64" => "long",
            "u64" => "ulong",
            "usize" => "nuint",
            "f32" => "float",
            "f64" => "double",
            "::std::os::raw::c_int" => "int",
            "::std::os::raw::c_uint" => "uint",
            "::std::os::raw::c_char" => "byte",
            "*mut ::std::os::raw::c_void" => "IntPtr",
            "*const ::std::os::raw::c_void" => "IntPtr",
            "*mut f32" => "IntPtr",
            "*const f32" => "IntPtr",
            "*mut i32" => "IntPtr",
            _ when rustType.StartsWith("transcribe_") => ToPascalCase(rustType),
            _ => "IntPtr"
        };
    }

    private static List<(string Type, string Name)> ParseParams(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw) || raw == "()")
            return new();

        var result = new List<(string Type, string Name)>();
        var depth = 0;
        var current = new StringBuilder();
        foreach (var ch in raw)
        {
            if (ch == '(' || ch == '<') depth++;
            else if (ch == ')' || ch == '>') depth--;
            else if (ch == ',' && depth == 0)
            {
                ParseOneParam(current.ToString().Trim(), result);
                current.Clear();
                continue;
            }
            current.Append(ch);
        }
        if (current.Length > 0)
            ParseOneParam(current.ToString().Trim(), result);
        return result;
    }

    private static void ParseOneParam(string raw, List<(string Type, string Name)> result)
    {
        var colonIdx = raw.IndexOf(':');
        if (colonIdx < 0) return;
        var name = raw[..colonIdx].Trim();
        var type = raw[(colonIdx + 1)..].Trim();
        result.Add((type, name));
    }

    private string ClassifyFunction(string name)
    {
        if (name.Contains("model")) return "Model";
        if (name.Contains("session")) return "Session";
        if (name.Contains("stream")) return "Streaming";
        if (name.Contains("batch")) return "Batch";
        if (name.Contains("segment")) return "Results — Segments";
        if (name.Contains("word")) return "Results — Words";
        if (name.Contains("token")) return "Results — Tokens";
        if (name.Contains("speaker")) return "Results — Speaker";
        if (name.Contains("timing")) return "Timings";
        if (name.Contains("backend") || name.Contains("device")) return "Backend";
        if (name.Contains("log")) return "Logging";
        if (name.Contains("version")) return "Version";
        if (name.Contains("abi")) return "ABI Metadata";
        return "Misc";
    }

    private static string ToPascalCase(string s)
    {
        s = Regex.Replace(s, @"^transcribe_", "", RegexOptions.IgnoreCase);
        var words = s.Split('_', StringSplitOptions.RemoveEmptyEntries);
        var result = new StringBuilder();
        foreach (var w in words)
        {
            if (w.All(char.IsUpper))
            {
                result.Append(char.ToUpper(w[0]));
                if (w.Length > 1)
                    result.Append(w[1..].ToLower());
            }
            else
            {
                result.Append(char.ToUpper(w[0]));
                if (w.Length > 1)
                    result.Append(w[1..]);
            }
        }
        return result.ToString();
    }

    private static string ToCamelCase(string s)
    {
        var pascal = ToPascalCase(s);
        var camel = pascal.Length > 0 ? char.ToLower(pascal[0]) + pascal[1..] : pascal;
        return "@" + camel;
    }
}
